version: "3"
services:
  jupyter:
    build: .
    ports:
      - "8888:8888" 
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./datos:/home/jovyan/work/datos 
    environment:
      - JUPYTER_ENABLE_LAB=yes 

